//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorSet
    {
        public int Id_actor { get; set; }
        public string Login { get; set; }
        public string Passowrd { get; set; }
        public int Admin_Id_admin { get; set; }
    
        public virtual AdminSet AdminSet { get; set; }
    }
}
