//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminSet
    {
        public AdminSet()
        {
            this.ActorSet = new HashSet<ActorSet>();
            this.ScoreSet = new HashSet<ScoreSet>();
        }
    
        public int Id_admin { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<ActorSet> ActorSet { get; set; }
        public virtual ICollection<ScoreSet> ScoreSet { get; set; }
    }
}
